package com.stg.cedh.maritz.processor;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.batch.item.ItemProcessor;

import com.stg.cedh.maritz.dto.CustomerSurveyDTO;
import com.stg.cedh.maritz.dto.EmailCaptureDTO;

public class CustomerSurveyProcessor implements ItemProcessor<CustomerSurveyDTO, CustomerSurveyDTO> {

	private static final Logger log = LoggerFactory.getLogger(EmailCaptureProcessor.class);

	@Override
	public CustomerSurveyDTO process(final CustomerSurveyDTO item) throws Exception {
		
		final String	eventType	=item.getEventType();
		final String	surveyType	=item.getSurveyType();
		final String	vINFirst9	=item.getVINFirst9();
		final String	vINLast8	=item.getVINLast8();
		final String	modelYear	=item.getModelYear();
		final String	bodyModelCode	=item.getBodyModelCode();
		final String	corpVehicleDescription	=item.getCorpVehicleDescription();
		final String	familyCode	=item.getFamilyCode();
		final String	customerID	=item.getCustomerID();
		final String	surveyStatus	=item.getSurveyStatus();
		final String	purchaseDate	=item.getPurchaseDate();
		final String	buildDate	=item.getBuildDate();
		final String	sampleDate	=item.getSampleDate();
		final String	receiptDate	=item.getReceiptDate();
		final String	zoneCode	=item.getZoneCode();
		final String	sALESDISTRICT	=item.getSALESDISTRICT();
		final String	salesGroupSize	=item.getSalesGroupSize();
		final String	brand	=item.getBrand();
		final String	dealerCode	=item.getDealerCode();
		final String	marketCode	=item.getMarketCode();
		final String	plantCode	=item.getPlantCode();
		final String	g_Date	=item.getG_Date();
		final String	repairNumber	=item.getRepairNumber();
		final String	repairDate	=item.getRepairDate();
		final String	sERVICEDISTRICT 	=item.getSERVICEDISTRICT();
		final String	salesPerson_SID	=item.getSalesPerson_SID();
		final String	financePerson_SID	=item.getFinancePerson_SID();
		final String	salesManager_SID	=item.getSalesManager_SID();
		final String	serviceAdvisor_SID	=item.getServiceAdvisor_SID();
		final String	technician_SID	=item.getTechnician_SID();
		final String	qGENDER	=item.getQGENDER();
		final String	qAGE	=item.getQAGE();
		final String	qMARITAL	=item.getQMARITAL();
		final String	qINCOME	=item.getQINCOME();
		final String	qArea	=item.getQArea();
		final String	qEducation	=item.getQEducation();
		final String	aR_QSalesAdvocacy	=item.getAR_QSalesAdvocacy();
		final String	aR_QBrandAdvocacy	=item.getAR_QBrandAdvocacy();
		final String	aR_QAvailableVehs	=item.getAR_QAvailableVehs();
		final String	aR_QAppearance	=item.getAR_QAppearance();
		final String	aR_QComfort	=item.getAR_QComfort();
		final String	aR_QFacility	=item.getAR_QFacility();
		final String	aR_QFollowThrough	=item.getAR_QFollowThrough();
		final String	aR_QVehKnowledge	=item.getAR_QVehKnowledge();
		final String	aR_QMeetNeeds	=item.getAR_QMeetNeeds();
		final String	aR_QCourteous	=item.getAR_QCourteous();
		final String	aR_QResponsive	=item.getAR_QResponsive();
		final String	aR_QHonest	=item.getAR_QHonest();
		final String	aR_QTabletDevice	=item.getAR_QTabletDevice();
		final String	aR_QTabletUse_VehNeeds	=item.getAR_QTabletUse_VehNeeds();
		final String	aR_QTabletUse_VehFeatures	=item.getAR_QTabletUse_VehFeatures();
		final String	aR_QTabletUse_CapturePersonalInfo	=item.getAR_QTabletUse_CapturePersonalInfo();
		final String	aR_QTabletUse_PricingPayment	=item.getAR_QTabletUse_PricingPayment();
		final String	aR_QTabletUse_Other	=item.getAR_QTabletUse_Other();
		final String	aR_QTabletUse_NoRecall	=item.getAR_QTabletUse_NoRecall();
		final String	aR_QTabletUse_VerbOther	=item.getAR_QTabletUse_VerbOther();
		final String	aR_QTestDrive	=item.getAR_QTestDrive();
		final String	aR_QTestDriveReason	=item.getAR_QTestDriveReason();
		final String	aR_QTestDriveReason_VerbOther	=item.getAR_QTestDriveReason_VerbOther();
		final String	aR_QSalesCons	=item.getAR_QSalesCons();
		final String	aR_QAgreementEase	=item.getAR_QAgreementEase();
		final String	aR_QClarity	=item.getAR_QClarity();
		final String	aR_QTimeFinalPaperwork	=item.getAR_QTimeFinalPaperwork();
		final String	aR_QFairness	=item.getAR_QFairness();
		final String	aR_QProfessional	=item.getAR_QProfessional();
		final String	aR_QWorkingOutDeal	=item.getAR_QWorkingOutDeal();
		final String	aR_QPressure	=item.getAR_QPressure();
		final String	aR_QExplainVehFeatures	=item.getAR_QExplainVehFeatures();
		final String	aR_QHandoff	=item.getAR_QHandoff();
		final String	aR_QTimeFinalDelivery	=item.getAR_QTimeFinalDelivery();
		final String	aR_QVehCondition	=item.getAR_QVehCondition();
		final String	aR_QConvenience	=item.getAR_QConvenience();
		final String	aR_QBluetooth	=item.getAR_QBluetooth();
		final String	aR_QVehCommunication	=item.getAR_QVehCommunication();
		final String	aR_QFeatureSetup	=item.getAR_QFeatureSetup();
		final String	aR_QDelivery	=item.getAR_QDelivery();
		final String	aR_QVehConditionDesc_Dings	=item.getAR_QVehConditionDesc_Dings();
		final String	aR_QVehConditionDesc_Dirty	=item.getAR_QVehConditionDesc_Dirty();
		final String	aR_QVehConditionDesc_MissingFeature	=item.getAR_QVehConditionDesc_MissingFeature();
		final String	aR_QVehConditionDesc_NoIssues	=item.getAR_QVehConditionDesc_NoIssues();
		final String	aR_QVehConditionDesc_Other	=item.getAR_QVehConditionDesc_Other();
		final String	aR_QVehConditionDesc_VerbOther	=item.getAR_QVehConditionDesc_VerbOther();
		final String	aR_QSalesExperience	=item.getAR_QSalesExperience();
		final String	aR_DealerSat_Verbatim	=item.getAR_DealerSat_Verbatim();
		final String	aR_DealerSat_Verbatim_Codes_Array	=item.getAR_DealerSat_Verbatim_Codes_Array();
		final String	aR_DealerSat_Verbatim_Codes_01	=item.getAR_DealerSat_Verbatim_Codes_01();
		final String	aR_DealerSat_Verbatim_Codes_02	=item.getAR_DealerSat_Verbatim_Codes_02();
		final String	aR_DealerSat_Verbatim_Codes_03	=item.getAR_DealerSat_Verbatim_Codes_03();
		final String	aR_QModelSat	=item.getAR_QModelSat();
		final String	aR_ModelSat_Verbatim	=item.getAR_ModelSat_Verbatim();
		final String	aR_ModelSat_Verbatim_Codes_Array	=item.getAR_ModelSat_Verbatim_Codes_Array();
		final String	aR_ModelSat_Verbatim_Codes_01	=item.getAR_ModelSat_Verbatim_Codes_01();
		final String	aR_ModelSat_Verbatim_Codes_02	=item.getAR_ModelSat_Verbatim_Codes_02();
		final String	aR_ModelSat_Verbatim_Codes_03	=item.getAR_ModelSat_Verbatim_Codes_03();
		final String	aR_QServAdvocacy	=item.getAR_QServAdvocacy();
		final String	aR_QTypeWorkExpressLane	=item.getAR_QTypeWorkExpressLane();
		final String	aR_QTypeWorkNotExpressLane	=item.getAR_QTypeWorkNotExpressLane();
		final String	aR_QTypeWorkWarranty	=item.getAR_QTypeWorkWarranty();
		final String	aR_QTypeWorkNonWarranty	=item.getAR_QTypeWorkNonWarranty();
		final String	aR_QTypeWorkRecall	=item.getAR_QTypeWorkRecall();
		final String	aR_QTypeWorkCollision_BodyRepair	=item.getAR_QTypeWorkCollision_BodyRepair();
		final String	aR_QTypeWorkOther	=item.getAR_QTypeWorkOther();
		final String	aR_QTypeWork_VerbOther	=item.getAR_QTypeWork_VerbOther();
		final String	aR_QFFV	=item.getAR_QFFV();
		final String	aR_QFFVReasons_Busy	=item.getAR_QFFVReasons_Busy();
		final String	aR_QFFVReasons_MoreWork	=item.getAR_QFFVReasons_MoreWork();
		final String	aR_QFFVReasons_NotFind	=item.getAR_QFFVReasons_NotFind();
		final String	aR_QFFVReasons_BrokeAgain	=item.getAR_QFFVReasons_BrokeAgain();
		final String	aR_QFFVReasons_PartsNA	=item.getAR_QFFVReasons_PartsNA();
		final String	aR_QFFVReasons_NotFixed	=item.getAR_QFFVReasons_NotFixed();
		final String	aR_QFFVReasons_NewProb	=item.getAR_QFFVReasons_NewProb();
		final String	aR_QFFVReasons_NotWarr	=item.getAR_QFFVReasons_NotWarr();
		final String	aR_QFFVReasons_NoAppt	=item.getAR_QFFVReasons_NoAppt();
		final String	aR_QFFVReasons_Other	=item.getAR_QFFVReasons_Other();
		final String	aR_QFFVReasons_DontKnow	=item.getAR_QFFVReasons_DontKnow();
		final String	aR_QFFVReasons_VerbOther	=item.getAR_QFFVReasons_VerbOther();
		final String	aR_FFVFix_Maint	=item.getAR_FFVFix_Maint();
		final String	aR_FFVFix_WarningIndic	=item.getAR_FFVFix_WarningIndic();
		final String	aR_FFVFix_Engine	=item.getAR_FFVFix_Engine();
		final String	aR_FFVFix_NoStart	=item.getAR_FFVFix_NoStart();
		final String	aR_FFVFix_Xmissn	=item.getAR_FFVFix_Xmissn();
		final String	aR_FFVFix_Brakes	=item.getAR_FFVFix_Brakes();
		final String	aR_FFVFix_SteerSuspn	=item.getAR_FFVFix_SteerSuspn();
		final String	aR_FFVFix_TiresWheels	=item.getAR_FFVFix_TiresWheels();
		final String	aR_FFVFix_Exterior	=item.getAR_FFVFix_Exterior();
		final String	aR_FFVFix_WaterWind	=item.getAR_FFVFix_WaterWind();
		final String	aR_FFVFix_Interior	=item.getAR_FFVFix_Interior();
		final String	aR_FFVFix_SqueakRattleVibr	=item.getAR_FFVFix_SqueakRattleVibr();
		final String	aR_FFVFix_NavAudioEnter	=item.getAR_FFVFix_NavAudioEnter();
		final String	aR_FFVFix_Electrical	=item.getAR_FFVFix_Electrical();
		final String	aR_FFVFix_HeatingAC	=item.getAR_FFVFix_HeatingAC();
		final String	aR_FFVFix_SunroofTop	=item.getAR_FFVFix_SunroofTop();
		final String	aR_FFVFix_Doors	=item.getAR_FFVFix_Doors();
		final String	aR_FFVFix_Recall	=item.getAR_FFVFix_Recall();
		final String	aR_FFVFix_Seats	=item.getAR_FFVFix_Seats();
		final String	aR_FFVFix_Access	=item.getAR_FFVFix_Access();
		final String	aR_FFVFix_Other	=item.getAR_FFVFix_Other();
		final String	aR_FFVFix_VerbOther	=item.getAR_FFVFix_VerbOther();
		final String	aR_QTimeComplete	=item.getAR_QTimeComplete();
		final String	aR_Q_ThoroughWork	=item.getAR_Q_ThoroughWork();
		final String	aR_QCondition	=item.getAR_QCondition();
		final String	aR_QKnowledge	=item.getAR_QKnowledge();
		final String	aR_QCourtesy	=item.getAR_QCourtesy();
		final String	aR_QResponsiveness	=item.getAR_QResponsiveness();
		final String	aR_QThoroughExplain	=item.getAR_QThoroughExplain();
		final String	aR_QFocused	=item.getAR_QFocused();
		final String	aR_QAdvice	=item.getAR_QAdvice();
		final String	aR_QVehInspect	=item.getAR_QVehInspect();
		final String	aR_StatusUpdate	=item.getAR_StatusUpdate();
		final String	aR_CostEstimate	=item.getAR_CostEstimate();
		final String	aR_Q_SERV_ADV	=item.getAR_Q_SERV_ADV();
		final String	aR_QEaseSched	=item.getAR_QEaseSched();
		final String	aR_QHowSched	=item.getAR_QHowSched();
		final String	aR_QDayWait	=item.getAR_QDayWait();
		final String	aR_QDaySat	=item.getAR_QDaySat();
		final String	aR_QTimelinessDropoff	=item.getAR_QTimelinessDropoff();
		final String	aR_QFacilityComfort	=item.getAR_QFacilityComfort();
		final String	aR_QFacilityEase	=item.getAR_QFacilityEase();
		final String	aR_QCleanFacility	=item.getAR_QCleanFacility();
		final String	aR_QTabletPurpose_CapturePersonalInfo	=item.getAR_QTabletPurpose_CapturePersonalInfo();
		final String	aR_QTabletPurpose_ServiceHistory	=item.getAR_QTabletPurpose_ServiceHistory();
		final String	aR_QTabletPurpose_Odometer	=item.getAR_QTabletPurpose_Odometer();
		final String	aR_QTabletPurpose_WorkToComplete	=item.getAR_QTabletPurpose_WorkToComplete();
		final String	aR_QTabletPurpose_IssueDetails	=item.getAR_QTabletPurpose_IssueDetails();
		final String	aR_QTabletPurpose_CostEstimate	=item.getAR_QTabletPurpose_CostEstimate();
		final String	aR_QTabletPurpose_Other	=item.getAR_QTabletPurpose_Other();
		final String	aR_QTabletPurpose_NoRecall	=item.getAR_QTabletPurpose_NoRecall();
		final String	aR_QTabletPurpose_VerbOther	=item.getAR_QTabletPurpose_VerbOther();
		final String	aR_QTransOffer	=item.getAR_QTransOffer();
		final String	aR_QTransType	=item.getAR_QTransType();
		final String	aR_QVehReady	=item.getAR_QVehReady();
		final String	aR_QAccuracyCost	=item.getAR_QAccuracyCost();
		final String	aR_QExplainCharges	=item.getAR_QExplainCharges();
		final String	aR_QWorkPerformed	=item.getAR_QWorkPerformed();
		final String	aR_QPickup	=item.getAR_QPickup();
		final String	aR_QFairCharges	=item.getAR_QFairCharges();
		final String	aR_QHelpful	=item.getAR_QHelpful();
		final String	aR_QServiceExperience	=item.getAR_QServiceExperience();
		final String	aR_DealerSuggestionVerbatim	=item.getAR_DealerSuggestionVerbatim();
		final String	aR_DealerSuggestionVerbatim_Codes_Array	=item.getAR_DealerSuggestionVerbatim_Codes_Array();
		final String	aR_DealerSuggestionVerbatim_Codes_01	=item.getAR_DealerSuggestionVerbatim_Codes_01();
		final String	aR_DealerSuggestionVerbatim_Codes_02	=item.getAR_DealerSuggestionVerbatim_Codes_02();
		final String	aR_DealerSuggestionVerbatim_Codes_03	=item.getAR_DealerSuggestionVerbatim_Codes_03();
		final String	cL_ContactYou	=item.getCL_ContactYou();
		final String	cL_Resolved	=item.getCL_Resolved();
		final String	cL_Advocacy	=item.getCL_Advocacy();
		final String	cL_Delivery	=item.getCL_Delivery();
		final String	cL_SlsConsult	=item.getCL_SlsConsult();
		final String	cL_SER_ADV	=item.getCL_SER_ADV();
		final String	cL_Comment	=item.getCL_Comment();
		final String	cL_Comment_Category_Codes_Array	=item.getCL_Comment_Category_Codes_Array();
		final String	cL_Comment_Category_Codes_01	=item.getCL_Comment_Category_Codes_01();
		final String	cL_Comment_Category_Codes_02	=item.getCL_Comment_Category_Codes_02();
		final String	cL_Comment_Category_Codes_03	=item.getCL_Comment_Category_Codes_03();
		final String	original_DlrAdvocacy	=item.getOriginal_DlrAdvocacy();
		final String	original_Delivery	=item.getOriginal_Delivery();
		final String	original_SlsConsultant	=item.getOriginal_SlsConsultant();
		final String	original_Serv_Advisor	=item.getOriginal_Serv_Advisor();
		final String	cL_InviteDate	=item.getCL_InviteDate();
		final String	cL_ReturnDate	=item.getCL_ReturnDate();
		final String	cL_Status	=item.getCL_Status();
		final String	uniqueID	=item.getUniqueID();
		final String	original_ReportMonth	=item.getOriginal_ReportMonth();
		final String	vehicleSaleType	=item.getVehicleSaleType();
		final String	languageCode	=item.getLanguageCode();
		final String	rPT_MONTH	=item.getRPT_MONTH();
		
		final CustomerSurveyDTO transformedCustomerSurveyDTO = new CustomerSurveyDTO(eventType, surveyType, vINFirst9, vINLast8, modelYear, bodyModelCode, corpVehicleDescription, familyCode, customerID, surveyStatus, purchaseDate, buildDate, sampleDate, receiptDate, zoneCode, sALESDISTRICT, salesGroupSize, brand, dealerCode, marketCode, plantCode, g_Date, repairNumber, repairDate, sERVICEDISTRICT, salesPerson_SID, financePerson_SID, salesManager_SID, serviceAdvisor_SID, technician_SID, qGENDER, qAGE, qMARITAL, qINCOME, qArea, qEducation, aR_QSalesAdvocacy, aR_QBrandAdvocacy, aR_QAvailableVehs, aR_QAppearance, aR_QComfort, aR_QFacility, aR_QFollowThrough, aR_QVehKnowledge, aR_QMeetNeeds, aR_QCourteous, aR_QResponsive, aR_QHonest, aR_QTabletDevice, aR_QTabletUse_VehNeeds, aR_QTabletUse_VehFeatures, aR_QTabletUse_CapturePersonalInfo, aR_QTabletUse_PricingPayment, aR_QTabletUse_Other, aR_QTabletUse_NoRecall, aR_QTabletUse_VerbOther, aR_QTestDrive, aR_QTestDriveReason, aR_QTestDriveReason_VerbOther, aR_QSalesCons, aR_QAgreementEase, aR_QClarity, aR_QTimeFinalPaperwork, aR_QFairness, aR_QProfessional, aR_QWorkingOutDeal, aR_QPressure, aR_QExplainVehFeatures, aR_QHandoff, aR_QTimeFinalDelivery, aR_QVehCondition, aR_QConvenience, aR_QBluetooth, aR_QVehCommunication, aR_QFeatureSetup, aR_QDelivery, aR_QVehConditionDesc_Dings, aR_QVehConditionDesc_Dirty, aR_QVehConditionDesc_MissingFeature, aR_QVehConditionDesc_NoIssues, aR_QVehConditionDesc_Other, aR_QVehConditionDesc_VerbOther, aR_QSalesExperience, aR_DealerSat_Verbatim, aR_DealerSat_Verbatim_Codes_Array, aR_DealerSat_Verbatim_Codes_01, aR_DealerSat_Verbatim_Codes_02, aR_DealerSat_Verbatim_Codes_03, aR_QModelSat, aR_ModelSat_Verbatim, aR_ModelSat_Verbatim_Codes_Array, aR_ModelSat_Verbatim_Codes_01, aR_ModelSat_Verbatim_Codes_02, aR_ModelSat_Verbatim_Codes_03, aR_QServAdvocacy, aR_QTypeWorkExpressLane, aR_QTypeWorkNotExpressLane, aR_QTypeWorkWarranty, aR_QTypeWorkNonWarranty, aR_QTypeWorkRecall, aR_QTypeWorkCollision_BodyRepair, aR_QTypeWorkOther, aR_QTypeWork_VerbOther, aR_QFFV, aR_QFFVReasons_Busy, aR_QFFVReasons_MoreWork, aR_QFFVReasons_NotFind, aR_QFFVReasons_BrokeAgain, aR_QFFVReasons_PartsNA, aR_QFFVReasons_NotFixed, aR_QFFVReasons_NewProb, aR_QFFVReasons_NotWarr, aR_QFFVReasons_NoAppt, aR_QFFVReasons_Other, aR_QFFVReasons_DontKnow, aR_QFFVReasons_VerbOther, aR_FFVFix_Maint, aR_FFVFix_WarningIndic, aR_FFVFix_Engine, aR_FFVFix_NoStart, aR_FFVFix_Xmissn, aR_FFVFix_Brakes, aR_FFVFix_SteerSuspn, aR_FFVFix_TiresWheels, aR_FFVFix_Exterior, aR_FFVFix_WaterWind, aR_FFVFix_Interior, aR_FFVFix_SqueakRattleVibr, aR_FFVFix_NavAudioEnter, aR_FFVFix_Electrical, aR_FFVFix_HeatingAC, aR_FFVFix_SunroofTop, aR_FFVFix_Doors, aR_FFVFix_Recall, aR_FFVFix_Seats, aR_FFVFix_Access, aR_FFVFix_Other, aR_FFVFix_VerbOther, aR_QTimeComplete, aR_Q_ThoroughWork, aR_QCondition, aR_QKnowledge, aR_QCourtesy, aR_QResponsiveness, aR_QThoroughExplain, aR_QFocused, aR_QAdvice, aR_QVehInspect, aR_StatusUpdate, aR_CostEstimate, aR_Q_SERV_ADV, aR_QEaseSched, aR_QHowSched, aR_QDayWait, aR_QDaySat, aR_QTimelinessDropoff, aR_QFacilityComfort, aR_QFacilityEase, aR_QCleanFacility, aR_QTabletPurpose_CapturePersonalInfo, aR_QTabletPurpose_ServiceHistory, aR_QTabletPurpose_Odometer, aR_QTabletPurpose_WorkToComplete, aR_QTabletPurpose_IssueDetails, aR_QTabletPurpose_CostEstimate, aR_QTabletPurpose_Other, aR_QTabletPurpose_NoRecall, aR_QTabletPurpose_VerbOther, aR_QTransOffer, aR_QTransType, aR_QVehReady, aR_QAccuracyCost, aR_QExplainCharges, aR_QWorkPerformed, aR_QPickup, aR_QFairCharges, aR_QHelpful, aR_QServiceExperience, aR_DealerSuggestionVerbatim, aR_DealerSuggestionVerbatim_Codes_Array, aR_DealerSuggestionVerbatim_Codes_01, aR_DealerSuggestionVerbatim_Codes_02, aR_DealerSuggestionVerbatim_Codes_03, cL_ContactYou, cL_Resolved, cL_Advocacy, cL_Delivery, cL_SlsConsult, cL_SER_ADV, cL_Comment, cL_Comment_Category_Codes_Array, cL_Comment_Category_Codes_01, cL_Comment_Category_Codes_02, cL_Comment_Category_Codes_03, original_DlrAdvocacy, original_Delivery, original_SlsConsultant, original_Serv_Advisor, cL_InviteDate, cL_ReturnDate, cL_Status, uniqueID, original_ReportMonth, vehicleSaleType, languageCode, rPT_MONTH);

        log.info("Converting (" + item + ") into (" + transformedCustomerSurveyDTO + ")");
		
		return transformedCustomerSurveyDTO;
	}

}
